# Generated by Django 3.1.1 on 2021-02-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='psw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='username',
        ),
    ]
